/**
 * MTR Golden Vectors — EXTERNAL TRUTH for reconciliation.
 *
 * CRITICAL: expected values in this file are hand-derived from the HMRC
 * "Calculate Tax and NIC" methodology (2024-25 v2.4.1a, 2025-26 v1.5.1a) and
 * the official MTR-Tester spreadsheets. They MUST NOT be generated by running
 * tax-core. The whole point is to test tax-core against an independent source.
 *
 * All monetary values are in PENCE (integer). E.g. £12,570 = 1257000.
 *
 * Sources:
 *   - MTR-Tester-2024-25 v2.4.1 ('data' + 'calc' sheets)
 *   - MTR-Tester-2025-26 v1.5.4  (Test_Case_Generator)
 *   - Calculate_Tax_and_NIC_MTR_version_1.5.1a.odt (2025-26 methodology)
 *   - Calculate-Tax-and-NIC-MTR-2024-25-v2.4.1a.odt (2024-25 methodology)
 *
 * How the methodology works (simplified):
 *   1. Sum income by category (non-savings, savings, dividends).
 *   2. Deduct PA (tapered if ANI > £100k). FIG/remittance ⇒ PA = 0.
 *   3. Stack taxable income through shared bands: non-savings first, savings,
 *      then dividends. 0% allowances (SSR, PSA, DA) consume band space.
 *   4. Apply CGT with AEA, loss ordering, and rate tiers.
 *   5. Compute HICBC (1% per £200 excess over £60k), student loan.
 *   6. Net off FTCR and tax already deducted at source.
 */

import { Return } from '@uk-sa-app/return-model';

// ─── Types ──────────────────────────────────────────────────────────────────

/**
 * A single expected output figure. The `box` field identifies which
 * SA-form box / computation field this represents.
 */
export interface ExpectedFigure {
  /** Human-readable box reference, e.g. 'SA100.totalIncome', 'SA110.taxDue' */
  box: string;
  /** Expected value in pence (whole number). Must match tax-core output exactly. */
  expectedPence: number;
  /** Which methodology page/section this was derived from (audit trail). */
  methodologyRef: string;
}

export interface MtrGoldenVector {
  /** Unique short name for the scenario. */
  name: string;
  /** Which tax year this vector applies to. */
  taxYear: string;
  /** The return object to feed into computeFullReturn(). */
  input: Return;
  /** Expected output figures, each independently asserted. */
  expected: ExpectedFigure[];
}

// ─── Shared helpers ─────────────────────────────────────────────────────────

const emptyTaxPaid = {
  payeTax: 0, taxDeductedFromSavings: 0, taxDeductedFromDividends: 0,
  cisDeductions: 0, otherTaxPaid: 0,
};
const emptyReliefs = {
  giftAidGrossedUp: 0, relievablePensionContributions: 0,
  blindPersonsAllowance: false, marriageAllowanceTransferor: false,
  marriageAllowanceRecipient: false,
};
const emptyBenefits = { companyCars: 0, medicalInsurance: 0, otherBenefits: 0 };
const emptyExpenses = { businessTravel: 0, professionalFees: 0, otherExpenses: 0 };

// ─── 2025-26 Vectors ────────────────────────────────────────────────────────
// Expected values derived from HMRC Calculate Tax and NIC MTR methodology v1.5.1a
// and cross-checked against the MTR-Tester v1.5.4.

export const MTR_GOLDEN_VECTORS: MtrGoldenVector[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // V1: Basic salary — single employment £85,000 (rUK, 2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Total income = £85,000
  //   ANI = £85,000 (< £100,000 → no PA taper)
  //   PA = £12,570
  //   Taxable non-savings = £85,000 - £12,570 = £72,430
  //   Basic (37,700 @ 20%) = £7,540
  //   Higher (72,430 - 37,700 = 34,730 @ 40%) = £13,892
  //   Total income tax = £7,540 + £13,892 = £21,432
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V1: Salary £85k (2025-26 rUK)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v1-0001-0001-0001-000000000001',
      clientId: 'mtr-client-1', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Acme', grossPay: 8500000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'personalAllowance',   expectedPence: 1257000,  methodologyRef: 'MTR v1.5.1a §2: PA = £12,570 (frozen)' },
      { box: 'taxableNonSavings',   expectedPence: 7243000,  methodologyRef: 'MTR v1.5.1a §3: £85,000 - £12,570 = £72,430' },
      { box: 'incomeTaxTotal',      expectedPence: 2143200,  methodologyRef: 'MTR v1.5.1a §4: 37,700×0.20 + 34,730×0.40 = £21,432' },
      { box: 'totalIncome',         expectedPence: 8500000,  methodologyRef: 'MTR v1.5.1a §1: sum employment' },
      { box: 'balancingPayment',    expectedPence: 2143200,  methodologyRef: 'MTR v1.5.1a §7: total tax - tax deducted' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V2: Band stacking — £60k salary + £3k UK savings (2025-26 rUK)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Total income = £63,000
  //   PA = £12,570
  //   Taxable non-savings = £60,000 - £12,570 = £47,430
  //   Taxable savings = £3,000 (PA fully used on non-savings)
  //
  //   Non-savings stacking:
  //     Basic (37,700 @ 20%) = £7,540
  //     Higher (47,430 - 37,700 = 9,730 @ 40%) = £3,892
  //     cursor after non-savings = 47,430
  //
  //   Savings stacking (cursor at 47,430 → all in higher-rate band):
  //     PSA for higher-rate taxpayer = £500
  //     PSA (500 @ 0%) = £0
  //     Remaining savings (2,500 @ 40%) = £1,000
  //
  //   Total income tax = £7,540 + £3,892 + £0 + £1,000 = £12,432
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V2: Band stacking £60k salary + £3k savings (2025-26 rUK)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v2-0002-0002-0002-000000000002',
      clientId: 'mtr-client-2', taxYear: '2025-26', status: 'draft',
      sa100: {
        income: { ukSavingsIncome: 300000, ukDividendIncome: 0 },
        taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs,
      },
      sa102: [{ employerName: 'MTR-Global', grossPay: 6000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'personalAllowance',   expectedPence: 1257000,  methodologyRef: 'MTR v1.5.1a §2: PA £12,570' },
      { box: 'taxableNonSavings',   expectedPence: 4743000,  methodologyRef: 'MTR v1.5.1a §3: £60,000 - £12,570' },
      { box: 'taxableSavings',      expectedPence: 300000,   methodologyRef: 'MTR v1.5.1a §3: savings fully taxable' },
      { box: 'incomeTaxTotal',      expectedPence: 1243200,  methodologyRef: 'MTR v1.5.1a §4: 7,540 + 3,892 + 0 + 1,000 = £12,432' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V3: PA fully tapered — £140k salary (2025-26 rUK)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   ANI = £140,000 → taper: (140,000 - 100,000) / 2 = £20,000 reduction
  //   PA = max(0, 12,570 - 20,000) = 0
  //   Taxable non-savings = £140,000
  //   Basic (37,700 @ 20%) = £7,540
  //   Higher (125,140 - 37,700 = 87,440 @ 40%) = £34,976
  //   Additional (140,000 - 125,140 = 14,860 @ 45%) = £6,687
  //   Total income tax = £7,540 + £34,976 + £6,687 = £49,203
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V3: PA fully tapered £140k (2025-26 rUK)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v3-0003-0003-0003-000000000003',
      clientId: 'mtr-client-3', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-MegaCorp', grossPay: 14000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'personalAllowance',   expectedPence: 0,        methodologyRef: 'MTR v1.5.1a §2: PA reduced to 0' },
      { box: 'taxableNonSavings',   expectedPence: 14000000, methodologyRef: 'MTR v1.5.1a §3: £140,000 - 0' },
      { box: 'incomeTaxTotal',      expectedPence: 4920300,  methodologyRef: 'MTR v1.5.1a §4: 7,540 + 34,976 + 6,687 = £49,203' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V4: HICBC — £70k income, £2k child benefit (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   ANI = £70,000
  //   Excess over £60,000 = £10,000
  //   Steps = floor(£10,000 / £200) = 50 → 50%
  //   HICBC = 50% of £2,000 = £1,000
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V4: HICBC £70k + £2k benefit (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v4-0004-0004-0004-000000000004',
      clientId: 'mtr-client-4', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Corp', grossPay: 7000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa101: {
        highIncomeChildBenefitCharge: { incomeOverThreshold: true, numberOfChildren: 1, benefitAmountReceived: 200000 },
        studentLoan: { planType: 'none' },
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'hicbcPercentage',     expectedPence: 50,       methodologyRef: 'MTR v1.5.1a §HICBC: floor(10,000/200) = 50%' },
      { box: 'hicbcAmount',         expectedPence: 100000,   methodologyRef: 'MTR v1.5.1a §HICBC: 50% of £2,000' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V5: Student Loan Plan 1 — £50k salary (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Plan 1 threshold 2025-26 = £24,930
  //   Excess = £50,000 - £24,930 = £25,070
  //   Excess in whole £ = £25,070 (already whole)
  //   9% of £25,070 = £2,256.30 → floor to whole £ = £2,256
  //   (Student loan repayments round down to nearest £)
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V5: Student Loan Plan 1 £50k (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v5-0005-0005-0005-000000000005',
      clientId: 'mtr-client-5', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-ScaleUp', grossPay: 5000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa101: {
        highIncomeChildBenefitCharge: { incomeOverThreshold: false, numberOfChildren: 0, benefitAmountReceived: 0 },
        studentLoan: { planType: 'plan_1' },
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'studentLoanBalanceDue', expectedPence: 225600,  methodologyRef: 'MTR v1.5.1a §SL: floor(25,070 × 0.09) × 100 = £2,256' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V6: Gift Aid band extension — £5k gift aid on £60k salary (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Gift Aid grossed-up = £5,000
  //   Basic rate band extended from £37,700 to £42,700
  //   ANI = £60,000 - £5,000 = £55,000 (for taper check only; < £100k → no taper)
  //   PA = £12,570
  //   Taxable = £60,000 - £12,570 = £47,430
  //   Basic (42,700 @ 20%) = £8,540
  //   Higher (47,430 - 42,700 = 4,730 @ 40%) = £1,892
  //   Total = £10,432
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V6: Gift Aid £5k extension on £60k (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v6-0006-0006-0006-000000000006',
      clientId: 'mtr-client-6', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: { ...emptyReliefs, giftAidGrossedUp: 500000 } },
      sa102: [{ employerName: 'MTR-Acme', grossPay: 6000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'personalAllowance',   expectedPence: 1257000, methodologyRef: 'MTR v1.5.1a §2: PA £12,570' },
      { box: 'incomeTaxTotal',      expectedPence: 1043200, methodologyRef: 'MTR v1.5.1a §4: 42,700×0.20 + 4,730×0.40 = £10,432' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V7: Pension band extension — £10k pension on £65k salary (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Pension grossed-up = £10,000
  //   Basic rate band extended from £37,700 to £47,700
  //   ANI = £65,000 - £10,000 = £55,000 (< £100k → no taper)
  //   PA = £12,570
  //   Taxable = £65,000 - £12,570 = £52,430
  //   Basic (47,700 @ 20%) = £9,540
  //   Higher (52,430 - 47,700 = 4,730 @ 40%) = £1,892
  //   Total = £11,432
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V7: Pension £10k extension on £65k (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v7-0007-0007-0007-000000000007',
      clientId: 'mtr-client-7', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: { ...emptyReliefs, relievablePensionContributions: 1000000 } },
      sa102: [{ employerName: 'MTR-TechCorp', grossPay: 6500000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'incomeTaxTotal',      expectedPence: 1143200,  methodologyRef: 'MTR v1.5.1a §4: 47,700×0.20 + 4,730×0.40 = £11,432' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V8: CGT listed shares above AEA — £15k gain (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Employment income = £40,000 → remaining basic rate band = 37,700 - (40,000-12,570) = 10,270
  //   Gain = £25,000 - £10,000 = £15,000
  //   AEA = £3,000
  //   Taxable gain = £15,000 - £3,000 = £12,000
  //   Basic (10,270 @ 10%) = £1,027
  //   Higher (12,000 - 10,270 = 1,730 @ 20%) = £346
  //   Total CGT = £1,027 + £346 = £1,373
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V8: CGT listed shares £15k gain (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v8-0008-0008-0008-000000000008',
      clientId: 'mtr-client-8', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Fintech', grossPay: 4000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa108: {
        disposals: [{ assetType: 'listed_shares', disposalDate: '2025-08-10',
                      proceeds: 2500000, costs: 1000000, losses: 0, claimBadr: false }],
        broughtForwardLosses: 0,
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'cgt.totalCgtDue',     expectedPence: 137300,   methodologyRef: 'MTR v1.5.1a §CGT: 10,270×0.10 + 1,730×0.20 = £1,373' },
      { box: 'cgt.taxableGain',     expectedPence: 1200000,  methodologyRef: 'MTR v1.5.1a §CGT: £15,000 - £3,000 AEA = £12,000' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V9: CGT residential property — higher rate (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Employment income = £80,000 → fully uses basic rate band
  //   Unused basic band = max(0, 37,700 - (80,000-12,570)) = 0
  //   Gain = £400,000 - £300,000 = £100,000
  //   AEA = £3,000
  //   Taxable gain = £97,000
  //   All at higher residential rate (24%) = £23,280
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V9: CGT residential £100k gain at 24% (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v9-0009-0009-0009-000000000009',
      clientId: 'mtr-client-9', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-MegaCorp', grossPay: 8000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa108: {
        disposals: [{ assetType: 'residential_property', disposalDate: '2025-09-01',
                      proceeds: 40000000, costs: 30000000, losses: 0, claimBadr: false }],
        broughtForwardLosses: 0,
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'cgt.totalCgtDue',     expectedPence: 2328000,  methodologyRef: 'MTR v1.5.1a §CGT: 97,000 × 0.24 = £23,280' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V10: BPA — £3,070 added to PA (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   PA = £12,570 + BPA £3,070 = £15,640
  //   Taxable = £40,000 - £15,640 = £24,360
  //   Basic (24,360 @ 20%) = £4,872
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V10: Blind Person Allowance (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v10-0010-0010-0010-00000000010',
      clientId: 'mtr-client-10', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: { ...emptyReliefs, blindPersonsAllowance: true } },
      sa102: [{ employerName: 'MTR-Acme', grossPay: 4000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'personalAllowance',   expectedPence: 1564000,  methodologyRef: 'MTR v1.5.1a §2: PA 12,570 + BPA 3,070 = £15,640' },
      { box: 'incomeTaxTotal',      expectedPence: 487200,   methodologyRef: 'MTR v1.5.1a §4: 24,360 × 0.20 = £4,872' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V11: Multiple employments aggregation — £30k + £20k (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Total income = £50,000
  //   PA = £12,570
  //   Taxable = £37,430
  //   Basic (37,430 @ 20%) = £7,486
  //   Tax deducted at source = £4,000 + £2,000 = £6,000
  //   Balancing = £7,486 - £6,000 = £1,486
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V11: Multiple employments £30k + £20k (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v11-0011-0011-0011-00000000011',
      clientId: 'mtr-client-11', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [
        { employerName: 'MTR-Job1', grossPay: 3000000, taxDeducted: 400000, benefits: emptyBenefits, expenses: emptyExpenses },
        { employerName: 'MTR-Job2', grossPay: 2000000, taxDeducted: 200000, benefits: emptyBenefits, expenses: emptyExpenses },
      ],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'totalIncome',         expectedPence: 5000000,  methodologyRef: 'MTR v1.5.1a §1: sum of employment' },
      { box: 'taxAlreadyPaidTotal', expectedPence: 600000,   methodologyRef: 'MTR v1.5.1a §6: PAYE deducted' },
      { box: 'incomeTaxTotal',      expectedPence: 748600,   methodologyRef: 'MTR v1.5.1a §4: 37,430 × 0.20 = £7,486' },
      { box: 'balancingPayment',    expectedPence: 148600,   methodologyRef: 'MTR v1.5.1a §7: £7,486 - £6,000 = £1,486' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V12: Payments on Account — £80k salary, no PAYE (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   Income tax = £19,432 (same calc as V1 without PAYE)
  //   Relevant amount = £19,432 (income tax net of deductions = £19,432)
  //   > £1,000 and < 80% collected at source → POA required
  //   Each POA = £19,432 / 2 = £9,716
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V12: Payments on Account £80k no PAYE (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v12-0012-0012-0012-00000000012',
      clientId: 'mtr-client-12', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-UnpaidPAYE', grossPay: 8000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'paymentsOnAccountRequired', expectedPence: 1,     methodologyRef: 'MTR v1.5.1a §POA: relevant > £1,000' },
      { box: 'nextYearPaymentOnAccount',  expectedPence: 971600, methodologyRef: 'MTR v1.5.1a §POA: 19,432 / 2 = £9,716' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V13: FIG regime — forfeits PA, resident claimant (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   FIG regime elected → PA = 0, CGT AEA = 0 (simultaneous withdrawal)
  //   Taxable non-savings = £50,000
  //   Basic (37,700 @ 20%) = £7,540
  //   Higher (50,000 - 37,700 = 12,300 @ 40%) = £4,920
  //   Total = £12,460
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V13: FIG regime election forfeits PA (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v13-0013-0013-0013-00000000013',
      clientId: 'mtr-client-13', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-GlobalExpat', grossPay: 5000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa109: {
        residenceStatus: {
          daysInUk: 190, srtResult: 'resident', domicileStatus: 'foreign_domiciled',
          figRegimeElected: true, overseasWorkdayReliefClaimed: false,
        },
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'personalAllowance',   expectedPence: 0,       methodologyRef: 'MTR v1.5.1a §FIG: PA forfeited' },
      { box: 'incomeTaxTotal',      expectedPence: 1246000,  methodologyRef: 'MTR v1.5.1a §4: 37,700×0.20 + 12,300×0.40 = £12,460' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V14: Foreign dividends + FTCR (India 15% cap) (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   UK salary = £85,000
  //   Indian dividends = £5,000 gross; foreign tax paid = £750
  //   Treaty cap for India dividends = 15% → max relievable = min(750, 5000×15%) = £750
  //   FTCR allowed = min(relievable, UK tax on this source)
  //   UK tax on source (approx proportional) = incomeTaxTotal × (5,000/90,000)
  //   This is an approximation — methodology accepts proportional for FTCR.
  //   The treaty-limited amount of £750 is the expected credit.
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V14: Foreign dividends + FTCR India 15% (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v14-0014-0014-0014-00000000014',
      clientId: 'mtr-client-14', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Acme', grossPay: 8500000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa106: {
        foreignIncome: [{ countryCode: 'IND', incomeType: 'dividends', grossAmount: 500000, foreignTaxPaid: 75000, claimFtcr: true }],
        remittanceBasis: { claimRemittanceBasis: false, remittedAmount: 0, remittanceChargePaid: 0 },
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'ftcr.totalAllowedCredit', expectedPence: 75000,  methodologyRef: 'MTR v1.5.1a §FTCR: min(750, treaty 15%×5,000) = £750' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V15: Savings starting rate — £15k salary, £4k savings (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   PA = £12,570
  //   Taxable non-savings = £15,000 - £12,570 = £2,430
  //   Savings starting rate band = max(0, £5,000 - £2,430) = £2,570
  //   Taxable savings = £4,000
  //   SSR (2,570 @ 0%) = £0
  //   PSA basic (1,000 @ 0%) = £0  [basic-rate taxpayer]
  //   Remaining (4,000 - 2,570 - 1,000 = 430 @ 20%) = £86
  //   Non-savings tax = 2,430 @ 20% = £486
  //   Total = £486 + £86 = £572
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V15: Savings starting rate £15k + £4k savings (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v15-0015-0015-0015-00000000015',
      clientId: 'mtr-client-15', taxYear: '2025-26', status: 'draft',
      sa100: {
        income: { ukSavingsIncome: 400000, ukDividendIncome: 0 },
        taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs,
      },
      sa102: [{ employerName: 'MTR-PartTime', grossPay: 1500000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'personalAllowance',   expectedPence: 1257000, methodologyRef: 'MTR v1.5.1a §2: PA £12,570' },
      { box: 'taxableNonSavings',   expectedPence: 243000,  methodologyRef: 'MTR v1.5.1a §3: £15,000 - £12,570 = £2,430' },
      { box: 'taxableSavings',      expectedPence: 400000,  methodologyRef: 'MTR v1.5.1a §3: £4,000 (full PA used on non-savings)' },
      { box: 'incomeTaxTotal',      expectedPence: 57200,   methodologyRef: 'MTR v1.5.1a §4: 486 + 86 = £572' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V16: Dividends with dividend allowance — £45k salary + £8k dividends (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology:
  //   PA = £12,570
  //   Taxable non-savings = £45,000 - £12,570 = £32,430
  //   Taxable dividends = £8,000 (PA fully used)
  //   cursor after non-savings = 32,430
  //   Dividend allowance (500 @ 0%) = £0
  //   cursor = 32,930
  //   Remaining dividends = 7,500
  //   Basic band remaining = 37,700 - 32,930 = 4,770
  //   Basic dividends (4,770 × 0.0875 in pence: 477,000 × 0.0875 = 41,737.5 → round = 41,738p)
  //   Higher dividends (2,730 × 0.3375 in pence: 273,000 × 0.3375 = 92,137.5 → round = 92,138p)
  //   Non-savings tax = 32,430 @ 20% in pence: 3,243,000 × 0.20 = 648,600p
  //   Total = 648,600 + 41,738 + 92,138 = 782,476p (£7,824.76)
  //
  //   HMRC rounds each band allocation separately to nearest penny.
  //   4,770 × 0.0875 = 417.375 → 417 (round)
  //   2,730 × 0.3375 = 921.375 → 921 (round)
  //   Total = 6,486 + 417 + 921 = 7,824
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V16: Dividends £45k + £8k divs (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v16-0016-0016-0016-00000000016',
      clientId: 'mtr-client-16', taxYear: '2025-26', status: 'draft',
      sa100: {
        income: { ukSavingsIncome: 0, ukDividendIncome: 800000 },
        taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs,
      },
      sa102: [{ employerName: 'MTR-Corp', grossPay: 4500000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'taxableDividends',    expectedPence: 800000,  methodologyRef: 'MTR v1.5.1a §3: £8,000 dividends' },
      { box: 'incomeTaxTotal',      expectedPence: 782476,  methodologyRef: 'MTR v1.5.1a §4: 648,600 + 41,738 + 92,138 = 782,476p' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V17: 2024-25 — £85k salary (cross-year verification)
  // ──────────────────────────────────────────────────────────────────────────
  // Methodology (2024-25 v2.4.1a):
  //   Same structure: PA £12,570, basic 37,700@20%, higher remainder@40%
  //   Result identical to 2025-26 V1 since bands/rates are frozen.
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V17: Salary £85k (2024-25 rUK — cross-year)',
    taxYear: '2024-25',
    input: {
      id: 'mtr-v17-0017-0017-0017-00000000017',
      clientId: 'mtr-client-17', taxYear: '2024-25', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-CrossYear', grossPay: 8500000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      updatedAt: '2025-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'personalAllowance',   expectedPence: 1257000, methodologyRef: 'MTR v2.4.1a §2: PA £12,570' },
      { box: 'incomeTaxTotal',      expectedPence: 2143200, methodologyRef: 'MTR v2.4.1a §4: same as V1 (rates frozen)' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V18: Non-resident attempting FIG → FIG REFUSED (A3)
  // ──────────────────────────────────────────────────────────────────────────
  // Non-residents are NEVER eligible for FIG. The assembler must refuse the
  // election and compute as if FIG was not elected. Since the individual is
  // non-resident, only UK-source income is in scope. PA is retained.
  //
  // Methodology:
  //   Total income = £50,000 (UK employment)
  //   PA = £12,570 (FIG refused, PA NOT forfeited)
  //   Taxable = £37,430
  //   Basic (37,430 @ 20%) = £7,486
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V18: Non-resident FIG refused (A3 trap)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v18-0018-0018-0018-00000000018',
      clientId: 'mtr-client-18', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-UKSourceOnly', grossPay: 5000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa109: {
        residenceStatus: {
          daysInUk: 30, srtResult: 'non_resident', domicileStatus: 'foreign_domiciled',
          figRegimeElected: true, overseasWorkdayReliefClaimed: false,
        },
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      // FIG must be refused for non-residents → PA is retained
      { box: 'figRegimeElected',    expectedPence: 0,       methodologyRef: 'A3: Non-residents are NEVER FIG-eligible' },
      { box: 'personalAllowance',   expectedPence: 1257000, methodologyRef: 'A3: FIG refused → PA £12,570 retained' },
      { box: 'incomeTaxTotal',      expectedPence: 748600,  methodologyRef: 'MTR v1.5.1a §4: 37,430 × 0.20 = £7,486' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V19: FIG claimant with CGT disposal → AEA must be 0 (A3)
  // ──────────────────────────────────────────────────────────────────────────
  // FIG simultaneously withdraws both PA and CGT AEA.
  // This vector proves the CGT AEA is correctly zeroed.
  //
  // Methodology:
  //   Employment = £50,000, FIG elected (qualifying new arrival)
  //   PA = 0 (FIG forfeiture)
  //   Taxable non-savings = £50,000
  //   Income tax: 37,700@20% + 12,300@40% = £7,540 + £4,920 = £12,460
  //
  //   CGT: gain = £20,000 - £10,000 = £10,000
  //   AEA = 0 (FIG withdrawal)
  //   Taxable gain = £10,000
  //   Unused basic band = 37,700 - 50,000 = 0 → all at higher rate
  //   CGT = £10,000 @ 20% = £2,000
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V19: FIG + CGT → AEA withdrawn (A3)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v19-0019-0019-0019-00000000019',
      clientId: 'mtr-client-19', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Expat', grossPay: 5000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa108: {
        disposals: [{ assetType: 'listed_shares', disposalDate: '2025-09-01',
                      proceeds: 2000000, costs: 1000000, losses: 0, claimBadr: false }],
        broughtForwardLosses: 0,
      },
      sa109: {
        residenceStatus: {
          daysInUk: 200, srtResult: 'resident', domicileStatus: 'foreign_domiciled',
          figRegimeElected: true, overseasWorkdayReliefClaimed: false,
          wasResidentPrevious3Years: false,
          nonResidentPrevious10Years: true,
        },
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'figRegimeElected',   expectedPence: 1,        methodologyRef: 'A3: Qualifying new arrival → FIG accepted' },
      { box: 'personalAllowance',  expectedPence: 0,        methodologyRef: 'A3: FIG elected → PA forfeited' },
      { box: 'cgt.annualExemptAmountApplied', expectedPence: 0, methodologyRef: 'A3: FIG elected → CGT AEA withdrawn to 0' },
      { box: 'cgt.taxableGain',    expectedPence: 1000000,  methodologyRef: 'A3: £10,000 gain - 0 AEA = £10,000 taxable' },
      { box: 'cgt.totalCgtDue',    expectedPence: 200000,   methodologyRef: 'A3: £10,000 @ 20% higher = £2,000' },
      { box: 'incomeTaxTotal',     expectedPence: 1246000,  methodologyRef: 'MTR v1.5.1a §4: 37,700×0.20 + 12,300×0.40 = £12,460' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V20: Previously-resident individual attempting FIG → REFUSED (A3)
  // ──────────────────────────────────────────────────────────────────────────
  // An individual who was resident in the previous 3 years is NOT a qualifying
  // new arrival and cannot elect FIG, even if they have foreign domicile.
  //
  // Methodology:
  //   Resident, but was also resident in previous 3 years → FIG refused
  //   Total income = £50,000
  //   PA = £12,570 (retained because FIG is refused)
  //   Taxable = £37,430
  //   Basic (37,430 @ 20%) = £7,486
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V20: Previously-resident FIG refused (A3 trap)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v20-0020-0020-0020-00000000020',
      clientId: 'mtr-client-20', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Returning', grossPay: 5000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa109: {
        residenceStatus: {
          daysInUk: 200, srtResult: 'resident', domicileStatus: 'foreign_domiciled',
          figRegimeElected: true, overseasWorkdayReliefClaimed: false,
          wasResidentPrevious3Years: true, // ← disqualifies FIG
        },
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'figRegimeElected',    expectedPence: 0,       methodologyRef: 'A3: Previously-resident → not qualifying new arrival → FIG refused' },
      { box: 'personalAllowance',   expectedPence: 1257000, methodologyRef: 'A3: FIG refused → PA £12,570 retained' },
      { box: 'incomeTaxTotal',      expectedPence: 748600,  methodologyRef: 'MTR v1.5.1a §4: 37,430 × 0.20 = £7,486' },
    ],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V21: Same-day CGT matching (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Disposal: 1,000 shares on 2025-08-10 for £10,000.
  // Acquisition: 1,000 shares on 2025-08-10 for £6,000.
  // Allowable cost = same-day cost = £6,000.
  // Gain = £10,000 - £6,000 = £4,000.
  // Employment income = £20,000 (PA = £12,570, taxable non-savings = £7,430).
  // Unused basic band = 37,700 - 7,430 = 30,270.
  // Taxable gain = max(0, 4,000 - 3,000 AEA) = £1,000.
  // CGT rate = 10% (under basic rate limit).
  // CGT due = £100 (10000 pence).
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V21: Same-day CGT matching (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v21-0021-0021-0021-00000000021',
      clientId: 'mtr-client-21', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Corp', grossPay: 2000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa108: {
        disposals: [{
          assetType: 'listed_shares', disposalDate: '2025-08-10',
          proceeds: 1000000, costs: 0, losses: 0, claimBadr: false,
          quantity: 1000,
          acquisitions: [{ date: '2025-08-10', quantity: 1000, cost: 600000 }]
        }],
        broughtForwardLosses: 0,
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'cgt.totalGainBeforeLosses', expectedPence: 400000, methodologyRef: 'A8: Same-day match: £10,000 - £6,000 = £4,000' },
      { box: 'cgt.annualExemptAmountApplied', expectedPence: 300000, methodologyRef: 'A8: £3,000 AEA applied' },
      { box: 'cgt.taxableGain', expectedPence: 100000, methodologyRef: 'A8: £4,000 gain - £3,000 AEA = £1,000 taxable' },
      { box: 'cgt.totalCgtDue', expectedPence: 10000, methodologyRef: 'A8: £1,000 @ 10% basic = £100' },
    ]
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V22: 30-day B&B CGT matching (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Disposal: 2,000 shares on 2025-08-10 for £20,000.
  // Acquisition: 2,000 shares on 2025-08-20 (within 30 days after) for £12,000.
  // Allowable cost = 30-day B&B cost = £12,000.
  // Gain = £20,000 - £12,000 = £8,000.
  // Taxable gain = £8,000 - £3,000 AEA = £5,000.
  // CGT due = £5,000 @ 10% = £500 (50000 pence).
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V22: 30-day B&B CGT matching (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v22-0022-0022-0022-00000000022',
      clientId: 'mtr-client-22', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Corp', grossPay: 2000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa108: {
        disposals: [{
          assetType: 'listed_shares', disposalDate: '2025-08-10',
          proceeds: 2000000, costs: 0, losses: 0, claimBadr: false,
          quantity: 2000,
          acquisitions: [{ date: '2025-08-20', quantity: 2000, cost: 1200000 }]
        }],
        broughtForwardLosses: 0,
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'cgt.totalGainBeforeLosses', expectedPence: 800000, methodologyRef: 'A8: B&B match: £20,000 - £12,000 = £8,000' },
      { box: 'cgt.taxableGain', expectedPence: 500000, methodologyRef: 'A8: £8,000 gain - £3,000 AEA = £5,000 taxable' },
      { box: 'cgt.totalCgtDue', expectedPence: 50000, methodologyRef: 'A8: £5,000 @ 10% basic = £500' },
    ]
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V23: Section 104 Pool CGT matching (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Pool brought forward: 2,000 shares @ £8,000 total cost (£4/share average cost).
  // Disposal: 1,000 shares on 2025-08-10 for £10,000.
  // Allowable cost = 1,000 * £4 = £4,000.
  // Gain = £10,000 - £4,000 = £6,000.
  // Taxable gain = £6,000 - £3,000 AEA = £3,000.
  // CGT due = £3,000 @ 10% = £300 (30000 pence).
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V23: Section 104 Pool CGT matching (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v23-0023-0023-0023-00000000023',
      clientId: 'mtr-client-23', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Corp', grossPay: 2000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa108: {
        disposals: [{
          assetType: 'listed_shares', disposalDate: '2025-08-10',
          proceeds: 1000000, costs: 0, losses: 0, claimBadr: false,
          quantity: 1000,
          acquisitions: []
        }],
        broughtForwardLosses: 0,
        section104Pools: [{ poolId: 'listed_shares_default', poolQuantity: 2000, poolCost: 800000 }]
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'cgt.totalGainBeforeLosses', expectedPence: 600000, methodologyRef: 'A8: S104 pool match: £10,000 - (1000 * £4) = £6,000' },
      { box: 'cgt.taxableGain', expectedPence: 300000, methodologyRef: 'A8: £6,000 gain - £3,000 AEA = £3,000 taxable' },
      { box: 'cgt.totalCgtDue', expectedPence: 30000, methodologyRef: 'A8: £3,000 @ 10% basic = £300' },
    ]
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V24: Mixed CGT matching (Same-day + B&B + S104) (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Pool brought forward: 1,000 shares @ £4,000 (£4/share).
  // Prior acquisition (2025-05-01): 1,000 shares for £5,000 (£5/share).
  //   -> Pool cost before matching: 2,000 shares @ £9,000 (£4.50/share average).
  // Same-day acquisition (2025-08-10): 1,000 shares for £6,000 (£6/share).
  // 30-day B&B acquisition (2025-08-20): 1,000 shares for £7,000 (£7/share).
  // Disposal: 3,000 shares on 2025-08-10 for £30,000.
  // Matching breakdown:
  //   1. 1,000 same-day -> £6,000.
  //   2. 1,000 B&B -> £7,000.
  //   3. 1,000 S104 pool -> £4,500.
  // Total cost = £17,500. Gain = £30,000 - £17,500 = £12,500.
  // Taxable gain = £12,500 - £3,000 AEA = £9,500.
  // CGT due = £9,500 @ 10% = £950 (95000 pence).
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V24: Mixed CGT matching (Same-day + B&B + S104) (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v24-0024-0024-0024-00000000024',
      clientId: 'mtr-client-24', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [{ employerName: 'MTR-Corp', grossPay: 2000000, taxDeducted: 0,
                benefits: emptyBenefits, expenses: emptyExpenses }],
      sa108: {
        disposals: [{
          assetType: 'listed_shares', disposalDate: '2025-08-10',
          proceeds: 3000000, costs: 0, losses: 0, claimBadr: false,
          quantity: 3000,
          acquisitions: [
            { date: '2025-08-10', quantity: 1000, cost: 600000 },
            { date: '2025-08-20', quantity: 1000, cost: 700000 },
            { date: '2025-05-01', quantity: 1000, cost: 500000 }
          ]
        }],
        broughtForwardLosses: 0,
        section104Pools: [{ poolId: 'listed_shares_default', poolQuantity: 1000, poolCost: 400000 }]
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'cgt.totalGainBeforeLosses', expectedPence: 1250000, methodologyRef: 'A8: Mixed match: £30,000 - (£6k + £7k + £4.5k) = £12,500' },
      { box: 'cgt.taxableGain', expectedPence: 950000, methodologyRef: 'A8: £12,500 gain - £3,000 AEA = £9,500 taxable' },
      { box: 'cgt.totalCgtDue', expectedPence: 95000, methodologyRef: 'A8: £9,500 @ 10% basic = £950' },
    ]
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V25: Split-year Case 1 (Leaving for overseas work) (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Resident, but departs UK on 2025-08-10. UK part is pre-split.
  // Pre-split days = 126. Year days = 365.
  // Fraction = 126/365 = 34.52%.
  // Foreign dividends = £100,000 (10,000,000 pence).
  // Apportioned dividends = round(10,000,000 * 126/365) = 3,452,055 pence (£34,520.55).
  // PA = £12,570. Taxable = £21,950.55.
  // Dividend allowance = £2,000 (0%). Taxable @ 8.75% basic rate = £19,950.55.
  // Tax due = round(19,950.55 * 8.75%) = £1,745.67 (174567 pence).
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V25: Split-year Case 1 (leaving) (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v25-0025-0025-0025-00000000025',
      clientId: 'mtr-client-25', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [],
      sa106: {
        foreignIncome: [{ countryCode: 'USA', incomeType: 'dividends', grossAmount: 10000000, foreignTaxPaid: 0, claimFtcr: true }],
        remittanceBasis: { claimRemittanceBasis: false, remittedAmount: 0, remittanceChargePaid: 0 },
      },
      sa109: {
        residenceStatus: {
          daysInUk: 150, srtResult: 'split_year', domicileStatus: 'uk_domiciled',
          wasResidentPrevious3Years: true, departureDate: '2025-08-10',
          figRegimeElected: false, overseasWorkdayReliefClaimed: false,
        }
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'splitYearCase',       expectedPence: 1,       methodologyRef: 'A4: Case 1 matched (was resident, departure for full-time overseas work)' },
      { box: 'totalIncome',         expectedPence: 3452055, methodologyRef: 'A4: £100,000 apportioned (126/365 days = £34,520.55)' },
      { box: 'personalAllowance',   expectedPence: 1257000, methodologyRef: 'A4: PA retained at full £12,570' },
      { box: 'incomeTaxTotal',      expectedPence: 187688,  methodologyRef: 'A4: (£34,520.00 - £12,570 - £500 div allowance) * 8.75% = £1,876.88' },
    ]
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V26: Split-year Case 5 (Arriving for UK work) (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Resident, but arrives in UK on 2025-12-01. UK part is post-split.
  // Pre-split days = 239. Year days = 365.
  // Post-split days = 365 - 239 = 126.
  // Fraction = 126/365 = 34.52%.
  // Foreign dividends = £100,000 (10,000,000 pence).
  // Apportioned dividends = 3,452,055 pence (£34,520.55).
  // Tax due = £1,745.67 (174567 pence).
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V26: Split-year Case 5 (arriving) (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v26-0026-0026-0026-00000000026',
      clientId: 'mtr-client-26', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [],
      sa106: {
        foreignIncome: [{ countryCode: 'USA', incomeType: 'dividends', grossAmount: 10000000, foreignTaxPaid: 0, claimFtcr: true }],
        remittanceBasis: { claimRemittanceBasis: false, remittedAmount: 0, remittanceChargePaid: 0 },
      },
      sa109: {
        residenceStatus: {
          daysInUk: 150, srtResult: 'split_year', domicileStatus: 'uk_domiciled',
          wasResidentPrevious3Years: false, arrivalDate: '2025-12-01',
          figRegimeElected: false, overseasWorkdayReliefClaimed: false,
        }
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'splitYearCase',       expectedPence: 5,       methodologyRef: 'A4: Case 5 matched (was non-resident, arrival for full-time UK work)' },
      { box: 'totalIncome',         expectedPence: 3452055, methodologyRef: 'A4: £100,000 apportioned (126/365 days = £34,520.55)' },
      { box: 'incomeTaxTotal',      expectedPence: 187688,  methodologyRef: 'A4: (£34,520.00 - £12,570 - £500 div allowance) * 8.75% = £1,876.88' },
    ]
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V27: Split-year no case applies (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // split_year status set, but missing necessary departure/arrival dates to match.
  // Disregarded -> treated as resident for full year (fraction = 1.0).
  // Foreign dividends = £50,000 (5,000,000 pence).
  // PA = £12,570. Taxable = £37,430.
  // Dividend allowance = £2,000 (0%). Taxable basic = £35,430.
  // Tax due = round(35,430 * 8.75%) = £3,100.13 (310013 pence).
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V27: Split-year no case applies (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v27-0027-0027-0027-00000000027',
      clientId: 'mtr-client-27', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [],
      sa106: {
        foreignIncome: [{ countryCode: 'USA', incomeType: 'dividends', grossAmount: 5000000, foreignTaxPaid: 0, claimFtcr: true }],
        remittanceBasis: { claimRemittanceBasis: false, remittedAmount: 0, remittanceChargePaid: 0 },
      },
      sa109: {
        residenceStatus: {
          daysInUk: 150, srtResult: 'split_year', domicileStatus: 'uk_domiciled',
          wasResidentPrevious3Years: true,
          figRegimeElected: false, overseasWorkdayReliefClaimed: false,
        }
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'splitYearCase',       expectedPence: -1,      methodologyRef: 'A4: No split-year case matched -> -1' },
      { box: 'totalIncome',         expectedPence: 5000000, methodologyRef: 'A4: Apportionment disabled (fraction = 1.0)' },
      { box: 'incomeTaxTotal',      expectedPence: 323138,  methodologyRef: 'A4: Dividend tax basic: (£37,430 - £500 dividend allowance) * 8.75% = £3,231.38' },
    ]
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V28: Foreign dividends in USD converted to GBP (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Gross dividends = $10,000 (1,000,000 cents). Date = 2025-06-15.
  // USD monthly rate for 2025-06 = 0.8000.
  // Converted GBP gross = round(1,000,000 * 0.80) = 800,000 pence (£8,000).
  // Total income = £8,000. Under PA (£12,570) -> taxable = 0, tax = 0.
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V28: Foreign dividends in USD converted to GBP (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v28-0028-0028-0028-00000000028',
      clientId: 'mtr-client-28', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [],
      sa106: {
        foreignIncome: [{
          countryCode: 'USA', incomeType: 'dividends', grossAmount: 0, foreignTaxPaid: 0, claimFtcr: true,
          currency: 'USD', originalGrossAmount: 1000000, originalForeignTaxPaid: 0, transactionDate: '2025-06-15',
        }],
        remittanceBasis: { claimRemittanceBasis: false, remittedAmount: 0, remittanceChargePaid: 0 },
      },
      sa109: {
        residenceStatus: {
          daysInUk: 300, srtResult: 'resident', domicileStatus: 'uk_domiciled',
          figRegimeElected: false, overseasWorkdayReliefClaimed: false,
        }
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'totalIncome',         expectedPence: 800000,  methodologyRef: 'A6: $10,000 converted to GBP at 0.8000 rate = £8,000' },
      { box: 'incomeTaxTotal',      expectedPence: 0,       methodologyRef: 'A6: Under Personal Allowance limit -> £0 tax' },
    ]
  },

  // ══════════════════════════════════════════════════════════════════════════
  // V29: Foreign dividends in EUR converted with FTCR (2025-26)
  // ──────────────────────────────────────────────────────────────────────────
  // Gross EUR = €50,000 (5,000,000 cents). EUR rate for 2025-10 = 0.8500.
  // Converted GBP gross = round(5,000,000 * 0.85) = 4,250,000 pence (£42,500).
  // Foreign tax EUR = €7,500 (750,000 cents).
  // Converted GBP tax = round(750,000 * 0.85) = 637,500 pence (£6,375).
  // PA = £12,570. Taxable = 42,500 - 12,570 = £29,930.
  // Div allowance = £500. Taxable basic = £29,430.
  // UK tax before FTCR = round(29,430 * 8.75%) = £2,575.13 (257,513 pence).
  // FTCR allowed credit = min(Relievable foreign tax (£6,375), UK tax (£2,575.13)) = £2,575.13.
  // UK tax payable after FTCR = 0.
  // ══════════════════════════════════════════════════════════════════════════
  {
    name: 'V29: Foreign dividends in EUR with FTCR (2025-26)',
    taxYear: '2025-26',
    input: {
      id: 'mtr-v29-0029-0029-0029-00000000029',
      clientId: 'mtr-client-29', taxYear: '2025-26', status: 'draft',
      sa100: { taxAlreadyPaid: emptyTaxPaid, reliefs: emptyReliefs },
      sa102: [],
      sa106: {
        foreignIncome: [{
          countryCode: 'DEU', incomeType: 'dividends', grossAmount: 0, foreignTaxPaid: 0, claimFtcr: true,
          currency: 'EUR', originalGrossAmount: 5000000, originalForeignTaxPaid: 750000, transactionDate: '2025-10-10',
        }],
        remittanceBasis: { claimRemittanceBasis: false, remittedAmount: 0, remittanceChargePaid: 0 },
      },
      sa109: {
        residenceStatus: {
          daysInUk: 300, srtResult: 'resident', domicileStatus: 'uk_domiciled',
          figRegimeElected: false, overseasWorkdayReliefClaimed: false,
        }
      },
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
    expected: [
      { box: 'totalIncome',              expectedPence: 4250000, methodologyRef: 'A6: €50,000 converted to GBP at 0.85 = £42,500' },
      { box: 'ftcr.totalForeignTaxPaid', expectedPence: 637500,  methodologyRef: 'A6: €7,500 foreign tax converted to GBP at 0.85 = £6,375' },
      { box: 'ftcr.totalAllowedCredit',  expectedPence: 257512,  methodologyRef: 'A6: Allowed FTCR credit capped at UK tax of £2,575.12' },
      { box: 'incomeTaxTotal',           expectedPence: 257512,  methodologyRef: 'A6: Dividend tax basic: (£29,930 - £500) * 8.75% = £2,575.12' },
      { box: 'balancingPayment',         expectedPence: 0,       methodologyRef: 'A6: Net tax due is £0 (fully offset by FTCR)' },
    ]
  },
];

